version: '3'

services:
  fastcgi-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local_network

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:8080"
    networks:
      - local_network
    depends_on:
      - fastcgi-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  local_network:
